group:
  security:
    name: Security
    entities:
      - alarm_control_panel.house
      - binary_sensor.front_door
      - binary_sensor.back_door

  zones:
    name: Zones
    entities:
      - binary_sensor.floorplan
      - binary_sensor.entry_kiosk
      - media_player.entry_kiosk
      - sun.sun

binary_sensor:
    - platform: mqtt
      name: "Front Door"
      state_topic: "/adtsecurity/FRelay02/FRL02"
      command_topic: "/adtsecurity/gpio/12"
      payload_on: 0
      payload_off: 1
      device_class: door
      optimistic: false
      retain: true

    - platform: mqtt
      name: "Back Door"
      state_topic: "/adtsecurity/BRelay01/BRL01"
      command_topic: "/adtsecurity/gpio/14"
      payload_on: 0
      payload_off: 1
      device_class: door
      optimistic: false
      retain: true
alert:
  alert_front_door_open:
    name: Front Door open
    done_message: Front Door closed
    entity_id: binary_sensor.front_door
    state: 'on'
    repeat:
      - 5
      - 20
      - 30
    skip_first: true
    notifiers:
      - telegram
      - html
  alert_back_door_open:
    name: back Door open
    done_message: Back Door closed
    entity_id: binary_sensor.back_door
    state: 'on'
    repeat:
      - 5
      - 20
      - 30
    skip_first: true
    notifiers:
      - telegram
      - html
