#################
### Google music
#################

input_select:
  music:
    name: Playlists
    options:
     - " "   # Should be empty
    icon: mdi:playlist-play
  media_player:
    name: Speakers
    options: # entity_ids of your media players
     - "living_room_speaker" # dads rooms
     - "basement_office_speaker"
     - "master_bedroom"
     - "basement_speaker"
     - "polk_assist"
     - "mataji_room_speaker"
     - "home_group" #everywhere
     - "havan_group"
     - "mataji__dad_group"
    icon: mdi:speaker-wireless
  radio_station:
    name: Select Radio Station
    options:
      - Radio Hindi 91.1
      - Evergreen Hits
      - Radio Mirchi 98.3
      - Radio City Hindi
    icon: mdi:radio

switch:
 - platform: gmusic
   user: !secret gmusic_user
   password: !secret gpassword
   device_id: !secret gmusic_device_id # http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
   media_player: media_player # entity id of the input select used for mediaplayer
   playlist: music # entity id of the input select used for playlist

#- platform: gmusic_radio
#   user: !secret gmusic_user
#   password: !secret gpassword
#   device_id: !secret gmusic_device_id # http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
#   media_player: media_player # entity id of the input select used for mediaplayer
#   playlist: music # entity id of the input select used for playlist

# group gmusic
group:
  Music:
    control: hidden
    name: Music
    entities:
      - input_select.media_player
      - input_number.volume_radio
      - input_select.music
      - switch.google_music
      - input_select.radio_station
      - input_boolean.play_radio
      - input_select.google_music


  cca:
    - media_player.livingroom
    - media_player.living_room_speaker
    - media_player.basement_office_speaker
    - media_player.master_bedroom
    - media_player.basement_speaker
    - media_player.polk_assist
    - media_player.mataji_room_speaker
    - media_player.home_group
    - media_player.havan_group
    - media_player.mataji__dad_group
#    - media_player.entry_kiosk


input_boolean:
  play_radio:
    name: Radio
    initial: off
    icon: mdi:play

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    initial: '0.2'

###   Do Not Delete   ###
shell_command:
  install_gmusic: pip3 install gmusicapi

automation:
  - alias: homeassistant_start_gmusic
    hide_entity: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: shell_command.install_gmusic

      
  - alias: Music Player - Play Radio
    initial_state: on
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.play_radio
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.google_music
      - service: media_player.volume_set
        data_template:
            entity_id: "media_player.{{ states('input_select.media_player') }}"
            volume_level: "{{ states('input_number.volume_radio') }}"
      - service: media_player.volume_mute
        data_template:
          entity_id: "media_player.{{ states('input_select.media_player') }}"
          is_volume_muted: false
      -  service: media_player.play_media
         data_template:
           entity_id: "media_player.{{ states('input_select.media_player') }}"
           media_content_id: >
            {% if is_state('input_select.radio_station' , 'Radio Hindi 91.1') %} http://prclive1.listenon.in:9960/
            {% elif is_state('input_select.radio_station' , 'Evergreen Hits') %} http://192.240.102.133:11454/stream/1/
            {% elif is_state('input_select.radio_station' , 'Radio Mirchi 98.3') %} http://peridot.streamguys.com:7150/Mirchi
            {% elif is_state('input_select.radio_station' , 'Radio City Hindi') %} http://prclive1.listenon.in:9960/ {% endif %}
           media_content_type: 'audio/mp4'

  - alias: Music Player - Stop Radio for GMusic
    hide_entity: true
    initial_state: on
    trigger:
      platform: state
      entity_id: switch.google_music
      to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.play_radio
      state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.play_radio

  - alias: Music Player - Sync volume
    hide_entity: true
    initial_state: on
    trigger:
      platform: state
      entity_id: input_number.volume_radio
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: "media_player.{{ states('input_select.media_player') }}"
          volume_level: "{{ states('input_number.volume_radio') }}"
      - service: media_player.volume_mute
        data_template:
          entity_id: "media_player.{{ states('input_select.media_player') }}"
          is_volume_muted: false

  - alias: Music Player - Stop all from Music Player
    hide_entity: true
    initial_state: on
    trigger:
      - platform: state
        entity_id:
          - input_boolean.play_radio
          - switch.google_music
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.play_radio
        state: 'off'
      - condition: state
        entity_id: switch.google_music
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: group.cca
      - service: input_number.set_value
        data_template:
          entity_id: input_number.volume_radio
          value: 0.20

  - alias: Music Player - Stop all from Media Player
    hide_entity: true
    initial_state: on
    trigger:
      platform: state
      entity_id: group.cca
      to: 'off'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.play_radio
          state: 'on'
        - condition: state
          entity_id: switch.google_music
          state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id:
        - input_boolean.play_radio
